config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing#index'


  match "/auth/:provider/callback" => 'sessions#create', as: "login_callback", via: [:get, :post]
  get 'logout', to: "sessions#destroy"
  resources :password_resets, only: [:show, :update, :new, :create]

  resource :session, only: [:new, :create]

  resources :voter_guides do
    resources :guide_reports, only: [:new, :create], as: :reports
    resources :supporters, only: [:create, :index]
    member do
      patch :publish
    end
  end

  resources :accounts, only: :show
  resources :email_confirmations, only: [:new, :create, :show]
  resources :unsubscribes, only: [:show, :update]

  resources :endorsements, only: :update
  resources :registrations, only: :new
  resources :guide_collections, only: [:index, :show]
end

app/controllers/landing_controller.rb
class LandingController < ApplicationController
  def index

  end
end

app/views/landing/index.html.erb
<div class="col-md-8 text-center">
  <div class="lowlight-header">
    <%= simple_form_for :search, url: voter_guides_path, method: :get do |f| %>
      <%= f.input :state, label: false, autofocus: true,
                  collection: GeographyPresenter::ELIGIBLE_STATES, include_blank: "Select State or click on map below to view local voter guides",
                  input_html: {id: "state_quickselect"} %>
    <% end %>
  </div>

  <small>
  </small>
  <p>&nbsp;</p>

  <div class=" lowlight-header1 visible-sm-block visible-md-block visible-lg-block visible-xs-block" >
    <div  style="width: 100%; height: 100%; overflow:hidden;position:relative;touch-action: none;" class="searchable_map_container">
      <div id="searchable_map" style="padding:20px;padding-top:0px;"></div>
    </div>
  </div>
  <p>&nbsp;</p>
  <div class="embed-responsive embed-responsive-16by9">
    <iframe class="embed-responsive-item" src="https://www.youtube.com/embed/_ecN8yT_9kQ"></iframe>
  </div>

  <p>&nbsp;</p>

  <% if VoterGuide.recommended.upcoming.published.any? %>
    <div class="highlight-block visible-md-block visible-lg-block">
    <h2>Featured Guides</h2>
      <div class="offset-list">
        <% VoterGuide.recommended.upcoming.includes(:supporters, :endorsements).published.order(published_at: :desc).limit(10).each do |vg| %>
          <%= render 'voter_guides/list_info_front_page', voter_guide: vg %>
        <% end %>
      </div>
    </div>
  <% end %>

  <% if VoterGuide.upcoming.published.any? %>
    <div class="highlight-block visible-md-block visible-lg-block">
      <h2>Recent Guides</h2>
      <div class="offset-list">
        <% VoterGuide.upcoming.published.includes(:supporters, :endorsements).order(published_at: :desc).limit(10).each do |vg| %>
          <%= render 'voter_guides/list_info_front_page', voter_guide: vg %>
        <% end %>
      </div>
    </div>
  <% end %>
</div>


<div class="col-md-4 text-center">
  <div class="shadowed-block">
    <h3 class="lowlight-header">
    <!--  502 guides and counting... -->

     <%= VoterGuide.upcoming.published.count %> Guides and Counting...


    </h3>
    <div class="lowlight-block">
      <h1><b>Browse Voter Guides</b></h1>
      <p>
        <%= link_to "create new guide", new_voter_guide_path, class: "btn btn-theballot btn-lg", role: "button" %>
      </p>
      <p>
        <%= link_to "view more guides", voter_guides_path, class: "btn btn-theballot btn-lg", role: "button" %>
      </p>
    </div>
  </div>

  <div class="lowlight-block text-left shadowed-block visible-md-block visible-lg-block">

    <h4><b>Do-It-Yourself Local Voter Guides</b></h4>
    <p>
  Honestly NO ONE knows how to vote down ballot! Find a LOCAL voter guide for your area, or create a guide that other people can use. Easy!

    </p>

  </div>

  <div class="highlight-block visible-md-block visible-lg-block">
    <a class="twitter-timeline"  href="https://twitter.com/hashtag/localballot" data-widget-id="775126658730766337" data-chrome="nofooter">#localballot Tweets</a>
    <script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+"://platform.twitter.com/widgets.js";fjs.parentNode.insertBefore(js,fjs);}}(document,"script","twitter-wjs");</script>
  </div>

  <div class="lowlight-block">
    <h4>Useful links</h4>
    <p><%= link_to "Find my polling place", "http://www.vote411.org/" %></p>
    <p><%= link_to "Am I Registered to Vote?", "https://www.vote.org/am-i-registered-to-vote/" %></p>
    <p><%= link_to "Vote Absentee", "https://www.vote.org/absentee-ballot/" %></p>
  </div>

</div>
<div class="col-xs-12">
  <div class="highlight-block">
    <h2>Partners</h2>
    <div class="text-center">

      <%= link_to "#" do %>
      <%= image_tag 'localballot/gamechanger_logo.png', alt: "Gamechanger Labs", class: 'partner-logo' %>
       <% end %> 

      <%= link_to "http://votemob.org/" do %>
      <%= image_tag 'localballot/vote_mob_logo.png', alt: "Vote Mob", class: 'partner-logo' %>
      <% end %> 

      <%= link_to "#" do %>
      <%= image_tag 'localballot/student_power_logo.png', alt: "Student Power", class: 'partner-logo' %>
      <% end %> 

      <%= link_to "#" do %>
      <%= image_tag 'localballot/LeagueLogo.png', alt: "LeagueLogo", class: 'partner-logo' %>
      <% end %> 

      <%= link_to "https://movement2016.org/" do %>
      <%= image_tag 'localballot/movement2016.png', alt: "Movement 2016", class: 'partner-logo' %>
      <% end %> 

    </div>
  </div>

<div class="container col-xs-12 col-md-9 text-center" style="float:none;text-align:center;">
 <!-- <center>
 <h6 style=" text-align:center;font-size:10px;width:799px;"> -->
    <div class="col-xs-12 col-md-12" style="text-align:center;font-size:10px;padding:0px">
Local Ballot is a voter guide platform paid for by All Hands on Deck Network, not by any candidate or candidate's committee. All views expressed here represent the views of individual voter guide creators, not necessarily of Local Ballot or All Hands on Deck Network. Treasurer: William Wimsatt 37 Kensington Ave, Northampton MA 01060.
</div>

</div>
</div>