config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing#index'


  match "/auth/:provider/callback" => 'sessions#create', as: "login_callback", via: [:get, :post]
  get 'logout', to: "sessions#destroy"
  resources :password_resets, only: [:show, :update, :new, :create]

  resource :session, only: [:new, :create]

  resources :voter_guides do
    resources :guide_reports, only: [:new, :create], as: :reports
    resources :supporters, only: [:create, :index]
    member do
      patch :publish
    end
  end

  resources :accounts, only: :show
  resources :email_confirmations, only: [:new, :create, :show]
  resources :unsubscribes, only: [:show, :update]

  resources :endorsements, only: :update
  resources :registrations, only: :new
  resources :guide_collections, only: [:index, :show]
end

app/models/voter_guide.rb
class VoterGuide < ApplicationRecord
  include SecureIdModel

  belongs_to :author, class_name: "User"
  has_many :endorsements, -> { order(:guide_order) }, dependent: :destroy
  has_many :supporters, dependent: :destroy
  has_many :guide_reports, dependent: :destroy

  validates :name, presence: true,
            uniqueness: {
              scope: [:target_city, :target_state],
              message: "should be unique for your area"}
  validates :target_state, presence: true
  validates :target_city, presence: false
  validates :election_date, presence: true
  validates :external_guide_url,
            format: { with: /\A#{URI::regexp(['http', 'https'])}\z/,
                      message: "must be a standard Web address",
                      allow_blank: true }

  accepts_nested_attributes_for :endorsements, reject_if: :all_blank, allow_destroy: true

  scope :upcoming, -> { where("election_date >= ?", Date.today)}
  scope :published, -> { where.not(published_at: nil) }
  scope :statewide, -> { where(statewide: true) }
  scope :recommended, -> { where.not(recommended_at: nil) }
  scope :by_state, ->(state) { where(target_state: state) }
  scope :by_zip, ->(zip) { GeographyPresenter.new(zip).search(VoterGuide) }

  def presenter
    @presenter ||= VoterGuidePresenter.new(self)
  end

  def published?
    published_at?
  end

  def recommended?
    recommended_at?
  end
end

app/controllers/voter_guides_controller.rb
class VoterGuidesController < ApplicationController
  before_action :require_login, except: [:show, :index]
  before_action :allow_guide_uploads, except: [:show, :publish, :index]
  load_and_authorize_resource find_by: :secure_id

  def new
    @voter_guide = VoterGuide.new election_date: Election.upcoming.first.try(:election_date)
  end

  def create
    @voter_guide = VoterGuide.new(voter_guide_params.merge(author: current_user))
    if @voter_guide.save
      GuidesReportingMailer.guide_created(@voter_guide.id).deliver_now
      redirect_to edit_voter_guide_path(@voter_guide)
    else
      render :new
    end
  end

  def show
  end

  def index
    search = VoterGuide
    search = search.by_zip(params[:search][:zip]) if params[:search] && params[:search][:zip]
    search = search.by_state(params[:search_state]) if params[:search_state]
    search = search.page(params[:page]).per(100).upcoming.published
    @voter_guides = search
  end

  def edit
  end

  def update
    if @voter_guide.update(voter_guide_params)
      redirect_to edit_voter_guide_path(@voter_guide)
    else
      render :edit
    end
  end

  def publish
    if current_user.email_confirmed?
      @voter_guide.touch :published_at
      flash[:notice] = "Guide has been published"
      redirect_to edit_voter_guide_path(@voter_guide)
    else
      confirmation = EmailConfirmation.create! user: current_user
      EmailConfirmationMailer.confirmation_code(confirmation.id).deliver_now
      redirect_to new_email_confirmation_path
    end
  end

  protected

  def voter_guide_params
    params.require(:voter_guide).permit(
      :name, :target_city, :target_state, :election_date, :external_guide_url, :statewide,
      endorsements_attributes:
        [:id, :_destroy,
         :initiative, :recommendation,
         :jurisdiction, :office, :candidate_name, :explanation, :highlight])
  end

  def allow_guide_uploads
    @upload_guide_target ||= UploadTarget.new("uploads")
  end

end

app/views/voter_guides/_core_info.html.erb
<h2><%= voter_guide.name %></h2>
<div><%= link_to "View Guide", voter_guide.presenter.show_url %></div>
<div><%= voter_guide.presenter.location_text %></div>
<div>Election: <%= voter_guide.election_date.strftime('%B %d, %Y') %></div>
<div>
  <% if voter_guide.published? %>
    Published on <%= voter_guide.presenter.publish_date %>
  <% else %>
    <div class="text-danger">DRAFT GUIDE</div>
    <% if can? :publish, voter_guide %>
      <%= link_to "Publish Now", publish_voter_guide_path(voter_guide), class: "btn btn-info", method: :patch %>
    <% end %>
  <% end %>
</div>

app/views/voter_guides/_endorsement.html.erb
<div>
  <%= endorsement.presenter.summary_text %>
</div>

app/views/voter_guides/_form.html.erb
<%= form.error :base, :error_method => :to_sentence %>
<%= form.input :name, label: "* Guide Title (ok if it's funny, but make sure to include the name of your city)
"  %>
<%= form.input :target_city, label: "Guide City", placeholder: "Indianapolis" %>
<%= form.input :statewide, label: "Statewide Guide", hint:"Statewide guides will not be connected to a specific city" %>
<%= form.input :target_state, label: "Guide State", collection: GeographyPresenter::ELIGIBLE_STATES, include_blank: "Select State" %>
<%= form.input :election_date, as: :datepicker %>

<h5>There are three ways to create a guide: upload a document, link to a guide on another website, or on the next page, enter individual endorsements. </h5>

<%= content_tag :div, nil, id:"voterguide_pdf_uploader", data: @upload_guide_target.data %>


<%= form.input :external_guide_url, label: "Upload Guide", as: :file, input_html: {accept: ".pdf", id: "guide_uploader"} %>

<h5>There are three ways to create a guide: upload a document, link to a guide on another website, or on the next page, enter individual endorsements. </h5>

<%= form.input :external_guide_url %>
<%= form.input :description, label: "What inspired you to write this guide?" %>

app/views/voter_guides/_list_info.html.erb
<style>
.fixed-box{
padding:1%;
margin:18px;
box-shadow:0px 0px 5px #727272;
background-color:#DED7B5; //#A7957A;
//width:30%;
width:93%;
float:left;
}
.media-left, .media-right, .media-body{
display:inherit;
}
.first-box{
background-color:#A7957A;
}
.media-right, .media > .pull-right {
    padding-left: 0px;
}
.underline {
    border-bottom: 3px solid #A7957A; 
  font-size:14px;
  font-weight:bold;
  height: 65px;
}
.endorsement{
color:#756348; 
}
/*.container {
    width: 1334px;
}*/
.highlight-block {
    background-color: #E9E0C2;
    margin-bottom: 20px;
    padding: 10px;
    text-align: left;
}
.endorsment-content{
  overflow: hidden;
  height: 90px;
} 
</style>
<div class="fixed-box">
<div class="media">
  <div class="col-md-12 media-left first-box">
    <div class="col-md-6 league-icon"></div>
    <h4 class="col-md-8"><%= link_to voter_guide.name, voter_guide.presenter.show_url, data: {guide_id: voter_guide.to_param}, target: "#{'blank' if voter_guide.external_guide_url.present?}" , :style => "color:black"%></h4>
  </div>
  <div class="col-md-12 media-right voterguide-summary">

    <div class="underline">
    <div><%= voter_guide.presenter.location_text %></div>
    <div>posted by <%= voter_guide.author.name %> / <%= voter_guide.election_date.strftime("%B %e, %Y")%>
      / <%= voter_guide.presenter.supporter_text %></div>
      </div>

    <% if voter_guide.presenter.show_endorsements? %>
    <div class="endorsment-content">
      <p class="endorsement"><%= voter_guide.endorsements.size %> endorsements</p>
      <% voter_guide.endorsements.highlighted.each do |endorsement | %>
        <%= render 'voter_guides/endorsement', endorsement: endorsement %>

      <% end %>
      </div>
      <%= link_to "more", voter_guide.presenter.show_url %>

    <% end %>
  </div>
</div>
</div>

app/views/voter_guides/_list_info_front_page.html.erb
<style>
.fixed-box{
box-shadow:0px 0px 5px #727272;
}
.media-left, .media-right, .media-body{
display:inherit;
}
.first-box{
background-color:#A7957A;
}
.media, .media-right, .media > .pull-right {
    padding: 6px;margin-bottom: 10px;background-color: #DED7B5;
}
.underline {
    border-bottom: 3px solid #A7957A; 
  font-size:14px;
  font-weight:bold;
  height: 45px;
  width:auto;
}
.endorsement{
color:#756348; 
}
/*.container {
    width: 1334px;
}*/
.highlight-block {
    background-color: #E9E0C2;
    margin-bottom: 20px;
    padding: 10px;
    text-align: left;
}
.endorsment-content{
  overflow: hidden;
  height: 90px;
}
.panel-heading {
    background-color: #A7957A none repeat scroll 0 0;
}
</style>
<div class="fixed-box">
<div class="media">
  <div class="media-left first-box">
    <div class="col-md-6 league-icon"></div>
    <h4 class="col-md-9"><%= link_to voter_guide.name, voter_guide.presenter.show_url, data: {guide_id: voter_guide.to_param}, target: "#{'blank' if voter_guide.external_guide_url.present?}" , :style => "color:black" %></h4> 
  </div>
  <div class="col-md-12 media-right voterguide-summary ">

    <div class="underline">
      <div><%= voter_guide.presenter.location_text %></div>
      <div>posted by <%= voter_guide.author.name %> / <%= voter_guide.election_date.strftime("%B %e, %Y")%>
        / <%= voter_guide.presenter.supporter_text %></div>
      </div>

    <% if voter_guide.presenter.show_endorsements? %>
    <div class="endorsment-content">
      <p class="endorsement"><%= voter_guide.endorsements.size %> endorsements</p>
      <% voter_guide.endorsements.highlighted.each do |endorsement | %>
        <%= render 'voter_guides/endorsement', endorsement: endorsement %>

      <% end %>
      </div>
      <%= link_to "more", voter_guide.presenter.show_url %>

    <% end %>
  </div>
</div>
</div>

app/views/voter_guides/edit.html.erb
<div class="highlight-block">
  <%= render 'core_info', voter_guide: @voter_guide %>
  <%= link_to "Edit Guide Fields", "#voter_guide_core_fields", data: {toggle: "collapse"}, aria: {controls: "voter_guide_core_fields", expanded: false} %>

  <%= simple_form_for @voter_guide, html: {multipart: true} do |f| %>
    <div class="collapse <%= "in" if @voter_guide.presenter.show_core_form? %>"  id="voter_guide_core_fields">
      <div class="well">
        <%= render 'voter_guides/form', form: f %>
        <%= f.button :submit, "Update", class: "btn btn-primary"  %>
      </div>
    </div>

    <% if @voter_guide.presenter.show_endorsements? %>
      <h3>Endorsements</h3>
      <%= render 'endorsements/toggle' %>
      <div id="endorsement_list" class="panel-group" role="tablist" aria-multiselectable="true">
        <%= f.simple_fields_for :endorsements do |endorsement| %>
          <% if endorsement.object.new_record? %>
            <%= render 'endorsements/edit_detail_with_errors', endorsement: endorsement.object, endorsement_form: endorsement %>
          <% else %>
            <%= render 'endorsements/edit_detail', endorsement: endorsement.object, endorsement_form: endorsement %>
          <% end %>
        <% end %>
      </div>
      <div id="endorsements">
        <div class="endorsements--links">
          <% if @voter_guide.endorsements.any? %>
            <p>
              <%= link_to_add_association 'Endorse Another Candidate', f, :endorsements, partial: 'endorsements/form', class: "btn btn-success" %>
            </p>
          <% else %>
            Next Step: Add some positions to your Guide
            <p>
              <%= link_to_add_association 'Endorse A Candidate', f, :endorsements, partial: 'endorsements/form', class: "btn btn-success" %>
            </p>
          <% end %>
          <p>
            <%= link_to_add_association 'Add a Ballot Initiative', f, :endorsements, partial: 'endorsements/initiative_form', class: "btn btn-success" %>
          </p>
        </div>
      </div>
      <p>&nbsp;</p>
      <p>
        <%= f.button :submit, "Save this Guide", class: "btn btn-primary"  %>
      </p>
    <% else %>
      <p>Endorsements are disabled because this guide references a file or external link.</p>
    <% end %>
  <% end %>

</div>

app/views/voter_guides/index.html.erb
<style>
.fixed-box{
padding:1%;
margin:10px;
box-shadow:0px 0px 5px #727272;
background-color:#DED7B5; //#A7957A;
//width:30%;
width:93%;
float:left;
}
.media-left, .media-right, .media-body{
display:inherit;
}
.first-box{
background-color:#A7957A;
}
.league-icon { 
    background-size: cover;
    border-radius: 6px;
    height: 100px;
    margin-left: -14px;
    width: 100px;
} 
.media-right, .media > .pull-right {
    padding-left: 0px;
}
.underline {
    border-bottom: 3px solid #A7957A; 
  font-size:14px;
  font-weight:bold;
}
.endorsement{
color:#756348; 
}
/*.container {
    width: 1334px;
}*/
.highlight-block {
    background-color: #E9E0C2;
    margin-bottom: 20px;
    padding: 10px;
    text-align: left;
    border-radius:10px;
}
</style>
<div class="col-xs-12 highlight-block">
<div class="highlight-block">
  <h2>Voter Guides</h2>

  <% if @voter_guides.empty? %>
    <p>No voter guides found for <%= params[:search_state] || params[:search][:zip] %></p>
    <p>
      <%= link_to "Make one now", new_voter_guide_path %>
    </p>
  <% else %>
    <div class="offset-list">
      <% @voter_guides.each do |voter_guide| %>
        <%= render 'list_info', voter_guide: voter_guide %>
      <% end %>
    </div>
    <%= paginate @voter_guides %>
  <% end %>
</div>

app/views/voter_guides/new.html.erb
<div class="lowlight-block">
  <h2>Create your voter guide</h2>

  <%= simple_form_for @voter_guide, html: {multipart: true} do |f| %>
    <%= render 'form', form: f %>
    <%= f.button :submit, "Ready", class: "btn btn-theballot"  %>
  <% end %>

</div>

app/views/voter_guides/show.html.erb
<div class="highlight-block"  style="background-color:#E9E0C2;">
  <h2><%= @voter_guide.name %></h2>
  <div><%= @voter_guide.presenter.location_text %>
    &nbsp;
    <%= link_to new_voter_guide_report_path(@voter_guide), title: "Report this Guide" do %>
      <span class="glyphicon glyphicon-warning-sign text-danger"></span>
      <span class="sr-only">Report this Guide</span>
    <% end %>
  </div>
  <div>Election: <%= @voter_guide.election_date.strftime('%B %d, %Y') %></div>
  <% if can? :edit, @voter_guide %>
    <div><%= link_to "Edit This Guide", edit_voter_guide_path(@voter_guide) %></div>
  <% end %>
  <div><%= @voter_guide.presenter.supporter_text %></div>
  <div class="fb-like" data-href="<%= voter_guide_url(@voter_guide) %>" data-layout="standard" data-action="like" data-size="small" data-show-faces="true" data-share="true"></div>

  <div class="hidden">
    <% if current_user && current_user.supports?(@voter_guide) %>
      <span class="glyphicon glyphicon-heart"></span>
      I support this guide.
    <% else %>
      <%= link_to voter_guide_supporters_path(@voter_guide), method: :post, class: "btn btn-success" do %>
        <span class="glyphicon glyphicon-heart"></span>
        Support this Guide
      <% end %>
    <% end %>
  </div>
  <% if @voter_guide.presenter.show_endorsements? %>
    <h3>Endorsements</h3>
    <%= render 'endorsements/toggle' %>
    <div id="endorsement_list" class="panel-group" role="tablist" aria-multiselectable="true">
      <% @voter_guide.endorsements.each do |endorsement| %>
        <%= render 'endorsements/detail', endorsement: endorsement, endorsement_form: nil %>
      <% end %>
    </div>
  <% else %>
    <p><%= link_to "Go to the Guide", @voter_guide.external_guide_url, target: :blank %></p>
  <% end %>
</div>
<%= content_for :open_graph do %>
  <meta property="og:url"         content="<%= voter_guide_url(@voter_guide) %>" />
  <meta property="og:type"        content="article" />
  <meta property="og:title"       content="<%= @voter_guide.name %>" />
  <meta property="og:description" content="<%= @voter_guide.presenter.share_description %>" />
  <meta property="og:image"       content="<%= image_url('theme/League_Header_01.gif') %>" />
<% end %>