config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing#index'


  match "/auth/:provider/callback" => 'sessions#create', as: "login_callback", via: [:get, :post]
  get 'logout', to: "sessions#destroy"
  resources :password_resets, only: [:show, :update, :new, :create]

  resource :session, only: [:new, :create]

  resources :voter_guides do
    resources :guide_reports, only: [:new, :create], as: :reports
    resources :supporters, only: [:create, :index]
    member do
      patch :publish
    end
  end

  resources :accounts, only: :show
  resources :email_confirmations, only: [:new, :create, :show]
  resources :unsubscribes, only: [:show, :update]

  resources :endorsements, only: :update
  resources :registrations, only: :new
  resources :guide_collections, only: [:index, :show]
end

app/views/layouts/_alerts.html.erb
<% if flash[:alert] %>
  <div class="alert alert-warning" role="alert"><%= flash[:alert] %></div>
<% end %>
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert"><%= flash[:notice] %></div>
<% end %>

app/views/layouts/_header.html.erb
<div class="localballot--header--top_stripes1  ">&nbsp;</div>


<header class="localballot--header">
  <div class="container">
    <nav class="navbar theballot--navbar" >
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header visible-sm-block visible-md-block visible-lg-block visible-xs-block" >
          <button type="button" class="navbar-toggle theballot--navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!--mycode start-->
         <%= link_to root_path do %>
           <div class= "navbar--logo"></div>
         <% end %> 
          <!--mycode end-->
          <%= link_to root_path, class: 'navbar--logo' do %>
  <!-- <img src="assets/localballot/logo.png" width="220px" height="50px"> -->

          <% end %>
        </div>
            <!--<div class="container">-->

        <div class="navbar-collapse theballot--navbar-collapse" id="bs-example-navbar-collapse-1">
          
          <ul class="nav navbar-nav navbar-right deskshow">
            <li><%= link_to "Create a Guide", new_voter_guide_path, class: 'user_nav--item' %></li>
            <% if current_user %>
              <li><%= link_to current_user.name, account_path(current_user), class: 'user_nav--item' %></li>
              <li><%= link_to "Log out", logout_path, class: 'user_nav--item' %></li>
            <% else %>
              <li><%= link_to "Log in  |  Sign Up", new_session_path, class: 'user_nav--item' %></li>

              <li><div class= "leaguelogo"></div> </li>
            <% end %>

          </ul>
        </div>
      <!--</div>-->
    </nav>
  </div>
</header>



<div class="localballot--header--bottom_stripes" style="border-top: 11px solid #e1f7b4; border-bottom: 4px solid black;"></div>
<div class="localballot--header--bottom_stripes" style=" border-bottom: 5px solid #397210;border-top: 11px solid #76c13a;height: 19px;"></div>
<div class="localballot--header--bottom_stripes" style=" border-top: 9px solid #397210;border-bottom: 0px solid #e1f7b4"></div>
<div style="padding:10px;width:100%;height:10px;"></div>

<div class="notshow">
  <ul class="container-fluid">
            <div class="siz2">
              <li class="siz1"><%= link_to "Create a Guide", new_voter_guide_path, class: 'user_nav--item' %></li>
            <% if current_user %>
              <li class="siz1"><%= link_to current_user.name, account_path(current_user), class: 'user_nav--item' %></li>
              <li class="siz1"><%= link_to "Log out", logout_path, class: 'user_nav--item siz' %></li>
            <% else %>
              <li class="siz1"><%= link_to "Log in  |  Sign Up", new_session_path, class: 'user_nav--item' %></li>
            </div>
              <li class="siz"><div class= "leaguelogo"></div> </li>
            <% end %>

          </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Voterguides</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta property="fb:app_id" content="<%= ENV['FACEBOOK_KEY'] %>" />
    <%= content_for :open_graph %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'setup_page', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" id="google-fonts-css" href="//fonts.googleapis.com/css?family=Arvo%3A700italic%7CLato%3A400%2C700%2C900%2C400italic&amp;ver=4.5.4" type="text/css" media="all">
  </head>

  <body>
    <%= render "layouts/header" %>
    <div class="container">
      <div class="row main-content">
        <div class="col-xs-12">
          <%= render 'layouts/alerts' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/landing.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Voterguides</title>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta property="fb:app_id" content="<%= ENV['FACEBOOK_KEY'] %>" />

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'setup_page', 'data-turbolinks-track': 'reload' %>
  <link rel="stylesheet" id="google-fonts-css" href="//fonts.googleapis.com/css?family=Arvo%3A700italic%7CLato%3A400%2C700%2C900%2C400italic&amp;ver=4.5.4" type="text/css" media="all">
</head>

<body>
  <%= render "layouts/header" %>
  <div class="container" style="background-color:#E9E0C2;border-radius:10px;padding-top:10px;">
    <div class="row main-content">
      <div class="col-xs-12">
        <%= render 'layouts/alerts' %>
      </div>
      <%= yield %>
    </div>
  </div>
</body>
</html>