config/routes.rb
Rails.application.routes.draw do
  ActiveAdmin.routes(self)
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'landing#index'


  match "/auth/:provider/callback" => 'sessions#create', as: "login_callback", via: [:get, :post]
  get 'logout', to: "sessions#destroy"
  resources :password_resets, only: [:show, :update, :new, :create]

  resource :session, only: [:new, :create]

  resources :voter_guides do
    resources :guide_reports, only: [:new, :create], as: :reports
    resources :supporters, only: [:create, :index]
    member do
      patch :publish
    end
  end

  resources :accounts, only: :show
  resources :email_confirmations, only: [:new, :create, :show]
  resources :unsubscribes, only: [:show, :update]

  resources :endorsements, only: :update
  resources :registrations, only: :new
  resources :guide_collections, only: [:index, :show]
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  load_and_authorize_resource class: "User", find_by: :secure_id

  def show
  end
end

app/views/accounts/show.html.erb
<div class="highlight-block">

<h2>Guides Authored by <%= @account.name %></h2>
  <% if @account.authored_voter_guides.any? %>
    <% @account.authored_voter_guides.order(created_at: :desc).each do |vg| %>
      <p>&nbsp;</p>
      <%= render 'voter_guides/core_info', voter_guide: vg %>
      <% if can? :edit, vg %>
        <%= link_to "Edit", edit_voter_guide_path(vg) %>
      <% end %>
    <% end %>
  <% else %>
    <p>You have not yet created any guides,
    <%= link_to "start one now", new_voter_guide_path %>
    </p>
  <% end %>
</div>